hashgraph/hedera-protobufs

- README.md
- services/ScheduleGetInfo.proto
- services/TransactionReceipt.proto
Addresses https://github.com/hashgraph/hedera-services/issues/1127.
- Allow any valid signer of a scheduled txn to query its receipt/record by returning the scheduled txn's `TransactionID` in the `TransactionReceipt` of any `ScheduleCreate` or `ScheduleSign` that resolves to `SUCCESS`.
- Allow any interested party to query for the receipt/record of a pending scheduled transaction by returning the scheduled txn's `TransactionID` in a `getScheduleInfo` response.
> Add scheduled transaction id to TransactionReceipt + ScheduleGetInfo types

- services/BasicTypes.proto
Resolves issue: #21 
Parent Issue : https://github.com/hashgraph/hedera-services/issues/750
Signed-off-by: anighanta <anirudh.ghanta@hedera.com>
> Fix Duplicated entries in AddressBook 0.0.101

- services/ResponseCode.proto
- services/ThrottleDefinitions.proto
For a candidate set of throttles in JSON form (as used to update the throttle defs file `0.0.123` with YAHCLI), please see [here](https://github.com/hashgraph/hedera-services/blob/new-throttling-spec/hedera-node/src/main/resources/throttles.json).
> Add ThrottleDefinitions types

- services/BasicTypes.proto
Allow the Services `getVersionInfo` query to [automatically return full info](https://github.com/hashgraph/hedera-services/pull/1339) on a deployed version via Maven property filtering.
- Add the `pre` and `build` fields from the [semver spec](https://semver.org/#spec-item-9) to our `SemanticVersion` proto type.
> Add full semver meta to SemanticVersion

- services/ResponseCode.proto
**If auto-renew is enabled**, Services will return `ACCOUNT_EXPIRED_AND_PENDING_REMOVAL` upon any query or transaction that tries to use an account that has expired with a zero balance.
Such accounts are in a "grace period" and not allowed to participate in normal operations.
> Add ACCOUNT_EXPIRED_AND_PENDING_REMOVAL response code

- services/Transaction.proto
previously deprecated fields are still needed to be able to historically parse valid transactions
> re-add deprecated fields to Transaction

- services/ResponseCode.proto
When the fractional custom fee `maximumAmount` is less than `minimumAmount`, add a new response code `FRACTIONAL_FEE_MAX_AMOUNT_LESS_THAN_MIN_AMOUNT`
**List of changes**:
Added `FRACTIONAL_FEE_MAX_AMOUNT_LESS_THAN_MIN_AMOUNT` to `ResponseCode.proto`
Fixes #45 
**Checklist**
> HIP-18 add missing response code

- services/BasicTypes.proto
- services/CustomFees.proto
- services/ResponseCode.proto
- services/TokenCreate.proto
- services/TokenFeeScheduleUpdate.proto
- services/TokenGetInfo.proto
- services/TokenService.proto
- services/TokenUpdate.proto
- services/TransactionBody.proto
- Avoid a later breaking change by adding a new `TokenFeeScheduleUpdate` transaction, which allows the `custom_fee_key` to have use consistent with the other "role" keys for KYC, freezing/unfreezing, etc.
**List of changes**:
- Add `HederaFunctionality` enum value `TokenFeeScheduleUpdate`.
- Add `TransactionBody` choice `TokenFeeScheduleUpdateTransactionBody`.
- Remove `CustomFees` wrapper and its use in `TokenUpdate`.
- Leave `repeated CustomFee custom_fees` in `TokenCreate` at top-level.
- Restore the `fee_schedule_key` to `TokenCreate`, `TokenUpdate`, and `TokenGetInfo`.
> Add TokenFeeScheduleUpdate op to allow switch back to fee_schedule_key

- services/ResponseCode.proto
Added response codes for if we a denominating token type is a NFT and one for when and NFT has a fractional fee in its feeSchedule
Signed-off-by: anighanta <anirudh.ghanta@hedera.com>
Fixes #48 
Related to https://github.com/hashgraph/hedera-services/issues/1722
> Add more responseCodes

- services/ResponseCode.proto
Add `INVALID_TOKEN_MINT_METADATA`, `INVALID_TOKEN_BURN_METADATA`, and `CURRENT_TREASURY_STILL_OWNS_NFTS`. (The last will be reused for a different response after `TokenUpdate` supports changing treasuries with non-zero NFTs.)
> HIP-17 response codes for v0.16.0-alpha.1 tag

- services/ResponseCode.proto
In the original implementation, the transaction fee payer account was responsible for paying the custom token fees. If the transaction fee-paying account did not have enough of the token to pay for the fee then INSUFFICIENT_PAYER_BALANCE_FOR_CUSTOM_FEE response was returned.
With the new implementation, the sender account is now responsible for paying the custom fees. When I see 'payer' in a response code I am thinking about the transaction fee payer account and not the sending account.
Solution
Update the response code to specify the sender account does not have enough token balance to pay for the custom fee.
INSUFFICIENT_SENDER_ACCOUNT_BALANCE_FOR_CUSTOM_FEE
https://github.com/hashgraph/hedera-services/issues/1825
Fixes # …
> Update response code

- services/Freeze.proto
This PR added a new field Timestamp as freeze start time, meanwhile deprecated these 4 fields as freeze start time and duration:
1. startHour
2. startMin
3. endHout
4. endMin
Now once hedera services enter `MAINTENANCE` mode, it has to be manually taken down and up.
Fixes #64
**Checklist**
> 064 d freeze txn use instant

- services/ResponseCode.proto
If HIP-17 is enabled, we will not initially allow more than 4,294,967,295 serial numbers to be used with a single unique token type.
> Response code for NFT serial no limit

- services/CustomFees.proto
- services/ResponseCode.proto
- Add a `repeated AccountID effective_payer_account_id` to the `AssessedCustomFee` message.
- Needed for https://github.com/hashgraph/hedera-services/issues/1938
> Add effective fee payers to transaction record

- services/CustomFees.proto
- services/ResponseCode.proto
- Define the `RoyaltyFee` message needed by https://github.com/hashgraph/hedera-services/issues/1935; please see that issue for details.
> Add RoyaltyFee custom fee type

- services/CustomFees.proto
Add `bool net_of_transfers` to `FractionalFee` message.
Needed for https://github.com/hashgraph/hedera-services/issues/1926
> Add `net_of_transfers` to `FractionalFee` message

- services/response_code.proto
Added a new response code `EXISTING_AUTOMATIC_ASSOCIATIONS_EXCEED_GIVEN_LIMIT` for Auto Association limit reached
**Checklist**
> Add response code for Auto Association limit reached

- services/response_code.proto
added a new response code for failure scenario where max automatic association limit is more than the `token.maxPerAccount`
Fixes #85 
**Checklist**
> Add a new response code for failure scenario where max automatic association limit is more than the `token.maxPerAccount`

- services/basic_types.proto
- services/network_get_execution_time.proto
- services/network_service.proto
- services/query.proto
- services/response.proto
Needed for https://github.com/hashgraph/hedera-services/issues/2099
- Some kinds of performance tests need fine-grained information on time spent handling specific `TransactionID`s.
- Without client-side access to this timing information, it becomes difficult to write self-validating perf tests.
- The new `NetworkService.getExecutionTime` query will only be enabled in DEV environments, to support such performance tests.
> Add (dev-only) `NetworkService.getExecutionTime` query

- services/token_service.proto
Mark the `FCOneToManyRelation`-based NFT queries as deprecated.
> Deprecate `getAccountNftInfos` and `getTokenNftInfos`

- services/token_service.proto
> Sync FCOTMR deprecation to `main`

- services/basic_types.proto
- Adds fields for ECDSA(secp256k1) public keys and signatures to the `Key` and `SignaturePair` types, respectively.
- Updates comments to reflect that only these two cryptography schemes are actually supported.
> Add ECDSA(secp256k1) fields to `Key` and `SignaturePair` messages

- services/basic_types.proto
- services/response_code.proto
- services/transaction_get_receipt.proto
- services/transaction_get_record.proto
- services/transaction_record.proto
- Adds response codes `REVERTED_SUCCESS` and `MAX_STORAGE_IN_PRICE_REGIME_HAS_BEEN_USED`.
- Supports child records via `TransactionID#nonce` and `TransactionRecord#parent_consensus_timestamp`.
- Permits querying for child receipts and records by parent `TransactionID`.
- Adds `delegatable_contract_id` key type.
> Protobuf changes for HIP-206

- services/basic_types.proto
- services/transaction_record.proto
Related to #118 
1. As per latest discussion [here](https://github.com/hashgraph/hedera-improvement-proposal/discussions/187#discussioncomment-1737239) , the `alias` is changed to `bytes` instead of `Key`.
2. Because mirror node need to maintain a map with all accounts and aliases as even after create , any transfer can be sent to an `alias`, the `alias <-> account` mapping is removed from `transaction_record`.
> Modifications for the auto account create

- services/response_code.proto
- services/transaction_record.proto
Related to #118 
1. Added a Response code `INVALID_ALIAS` when the alias is not valid primitive key
2. Added `alias` to transaction record that will be set for `CryptoCreate` transaction record
> Auto account creation changes

- services/basic_types.proto
- services/response_code.proto
- Adds a `TokenTransferList#expected_decimals` field so clients can stipulate a fungible token transfer will only succeed if the actual decimals match the field's value.
- Adds a `UNEXPECTED_TOKEN_DECIMALS` for the failure case.
> Support HIP-31

- services/crypto_update.proto
- services/response_code.proto
Closes #134 
For extending alias support to all transactions and Queries, added additional response codes to be returned if account ID given is invalid or does not exist.
> Additional response codes for extending alias support

- services/basic_types.proto
- services/contract_call.proto
- services/contract_call_local.proto
- services/transaction_record.proto
Prepares for `CREATE2` implementation.
1. Allows HAPI clients to use a `ContractID` to target a contract either by its number **or** its EVM address.
2. Deprecates the `ContractFunctionResult#createdContractIDs` field, which will be superseded by `ContractID`s externalized in the record stream via "child transactions".
3. Adds a `bytes evm_address` to the `ContractFunctionResult`, to be populated in the record of each contract creation (whether top-level or internal).
> Populate `evm_address` in contract create record and support use in HAPI 

- services/contract_call_local.proto
> Use `BytesValue` for result `evm_address` to make its potential absence explicit

- mirror/mirror_network_service.proto
[HIP-21](https://hips.hedera.com/hip/hip-21) Add a mirror node gRPC API to get node addresses from an address book.
**Checklist**
> HIP-21 Add a mirror API to get node addresses

- services/crypto_adjust_allowance.proto
- services/crypto_approve_allowance.proto
- services/crypto_service.proto
- services/schedulable_transaction_body.proto
- services/transaction_body.proto
- Add approve and adjust allowance bodies to the `TransactionBody` and `SchedulableTransactionBody` choices.
- Add approve/adjust transactions to the `CryptoService`.
- Clarify in comments that spender allowances are against _the payer account_ of the `approveAllowances` or `adjustAllowance` transaction.
> Address reviewer comments

- services/crypto_adjust_allowance.proto
- services/crypto_approve_allowance.proto
- services/crypto_get_info.proto
- services/crypto_service.proto
- services/response_code.proto
- services/schedulable_transaction_body.proto
- services/transaction_body.proto
Signed-off-by: Albert Tam <albert.tam@hedera.com>
Modified CryptoGetInfoResponse to include hbar/token allowances approved by the account owner. Added CryptoApproveAllowanceTransactionBody and CryptoAdjustAllowanceTransactionBody messages for an account owner to establish new allowances and modify existing allowances respectively.
Changes made as outlined in HIP 336.
Fixes #132
**Checklist**
> Added messages for approval/allowance feature (HIP 336)

- services/basic_types.proto
The main problem we're trying to solve is how to differentiate regular transfers involving the spender + owner versus a transfer that uses an allowance. We need to make this determination with minimal use of expanding signatures during `handleTransaction`.
The agreed upon approach is to add `is_approval` fields to `AccountAmount` and `NftTransfer`. The presence of the flag indicates that:
- The `accountID` should be treated as the allowance owner
- A signature check of the owner is not necessary as long as an allowance for the caller is present
The same approach holds for the NFT case.
Fixes #132
Positioning the flag at this level grants us the flexibility of having approved transfers intermingled with regular transfers in a …
> Added is_approval flags for transfers to indicate allowance checks should be done

- services/basic_types.proto
- services/response_code.proto
Add owner field to `CryptoAllowance`, `TokenAllowance` and `NftAllowance`. Currently we infer the owner for approval and adjustment transactions as the sender account. Eventually, when we move to emitting the `Allowance` messages as part of the periodic account balances (for mirror node), the allowances will require the owner in order to make sense.
Reordered the fields in Allowances to place owner higher. Since we haven't released the feature yet, decided to renumber now to have fields placed in order of significance.
**Checklist**
> Added owner field to Allowance messages

- services/crypto_update.proto
Revert updating alias using `CryptoUpdate` as the feature is extended to 0.24 release
> Revert updating alias 

- services/contract_call_local.proto
Add precompiled call data for parameters, gas, and amount to the
ContractFunctionResults. These would be in the TransactionBody
if it was a normal call but the body for precompiles is a
different type,
Signed-off-by: Danno Ferrin <danno.ferrin@hedera.com>
Fixes #157
**Checklist**
> Add precompile call data to ContractFunctionResults

- services/basic_types.proto
- services/crypto_delete_allowance.proto
- services/crypto_service.proto
- services/response_code.proto
- services/schedulable_transaction_body.proto
- services/token_get_nft_info.proto
- services/transaction_body.proto
Signed-off-by: Albert Tam <albert.tam@hedera.com>
Added CryptoDeleteAllowanceTransactionBody and inner messages xDeleteAllowance (crypto, nft, token) for new HAPI operation CryptoDeleteAllowance.
Operation allows callers to delete all allowances without specifying the spender.
Fixes #164
**Checklist**
> Add transaction body and inner messages for CryptoDeleteAllowance

- services/basic_types.proto
- services/crypto_delete_allowance.proto
- services/crypto_service.proto
- services/response_code.proto
- services/transaction_record.proto
Signed-off-by: Neeharika-Sompalli <neeharika.sompalli@hedera.com>
- Since there is no more a map in account state with list of serials for NFTs and is moved to `MerkleUniqueToken` , removing it from the getAccountInfo `GrantedNftAllowance`
> Remove serials in GetAccountInfo for NFT allowances

- services/response_code.proto
- services/schedule_delete.proto
- services/schedule_sign.proto
add response code for when a schedule is still in the db yet it is expired
Fixes #183
**Checklist**
> fix(#183): add response code for when a schedule is still in the db yet it is expired

- services/basic_types.proto
- services/schedule_create.proto
Add a sub type for schedule create with a contract call fees, clarify docs on schedule create
Fixes #
**Checklist**
> fix(#183): add schedule create sub fee type, clairify some docs

- services/basic_types.proto
- services/contract_create.proto
- services/contract_delete.proto
- services/contract_update.proto
- services/response_code.proto
**Related issues**:
- Closes #176 
- Closes #177 
- Adds fields to `ContractCreate-` and `ContractUpdateTransactionBody` messages to allow creating and updating contracts with both an auto-renew account and auto-association slots.
- Adds a few response codes needed to give contract-specific failure statuses.
- Adds a `bool permanent_removal` flag to `ContractDeleteTransactionBody` for use in a synthetic removal record.
> Include fields needed for contract expiry and auto-association semantics

- services/contract_create.proto
- services/transaction_body.proto
Renumber and move `TransactionBody.ethereumTransaction`. - remove gap at 50
Renumber `ContractCreateTransactionBody.initcode` - preserver historical gap at 7
Signed-off-by: Danno Ferrin <danno.ferrin@hedera.com>
> Renumber and Reorder Ethereum entries

- services/contract_get_info.proto
Fixes #176 
- Add `auto_renewal_account_id` to `ContractGetInfo`
> Additional changes for smart contract expiry

- services/response_code.proto
Signed-off-by: Neeharika-Sompalli <neeharika.sompalli@hedera.com>
Since , we accepted duplicate entries in allowance transaction bodies , adding `deprecated =true` for all old response codes. These are not being deleted because some old version of allowance changes used them
> Add deprecated tag to deprecated response codes

- services/contract_get_info.proto
Signed-off-by: Neeharika-Sompalli <neeharika.sompalli@hedera.com>
Related to #177 
- Add the `max_automatic_token_associations` to `contract_get_info`
> Add max_token_associations to contract_info

- services/basic_types.proto
- services/contract_create.proto
- services/contract_get_info.proto
- services/contract_update.proto
- services/crypto_create.proto
- services/crypto_get_info.proto
- services/crypto_update.proto
- services/get_account_details.proto
- services/response_code.proto
- services/transaction_record.proto
Fixes #169  #170  #171 #172 #173 #174 #175
- Deprecated `proxyAccountID` in `(Crypto/Contract)CreateTransactionBody` , `(Crypto/Contract)UpdateTransactionBody`, (Crypto/Contract)GetInfo
- Deprecated `NodeAddress#stake`
- Added new staking fields to `(Crypto/Contract)CreateTransactionBody` , `(Crypto/Contract)UpdateTransactionBody`
- Added `StakingInfo` and returned in `(Crypto/Contract)GetInfo` query
- Added `paid_staking_rewards` to `TransactionRecord`
- Added ResponseCodes needed
> Staking changes

- services/basic_types.proto
- services/node_stake_update.proto
- services/transaction_body.proto
Related to #175 
- Added `NodeStakeUpdateTransactionBody` which will be used for sending end of staking period values for transaction record
> `NodeStakeUpdateTransactionBody` for end of period staking info

- services/node_stake_update.proto
- Moves `reward_rate` into the `NodeStake` message and adds more detail in comments.
- Fixes descriptions of `stake_rewarded` and `stake` fields per @xin-hedera.
> Publish reward rates per node

- services/node_stake_update.proto
Add fields to export the following staking Services properties:
```
staking.fees.nodeRewardPercentage=0                                              
staking.fees.stakingRewardPercentage=100                                         
staking.maxDailyStakeRewardThPerH=17_808                                                                                           
staking.rewardRate=0                                                         
staking.startThreshold=250_000_000_00_000_000
staking.periodMins=1440
staking.rewardHistory.numStoredPeriods=365
```
> Add more staking metadata to `NodeStakeUpdate` message

- services/basic_types.proto
- services/response_code.proto
- services/schedulable_transaction_body.proto
- services/transaction_body.proto
- services/transaction_record.proto
- services/util_prng.proto
- services/util_service.proto
Related to HIP-351 .
Change name of `prng` transaction to `utilPrng` as per latest discussion, to maintain naming standards for the transaction and transaction body.
> Hip-351 : Change name of `prng` txn to `utilPrng`

- services/contract_get_info.proto
- services/crypto_get_account_balance.proto
- services/crypto_get_info.proto
- Mark several fields `deprecated` that will be removed in Nov release (c.f. [here](https://www.notion.so/swirldslabs/HIP-367-Token-Information-Deprecation-15aff829f32f488b90cbc3732b17d305)).
> Deprecate token relationships fields

- streams/contract_action.proto
Signed-off-by: lukelee-sl <luke.lee@swirldslabs.com>
Add CallOperationType enum.  This will be used to track the specific operation associated with a given contract action.
Fixes #221 
**Checklist**
> add CallOperationType enum and corresponding field to ContractAction

- services/basic_types.proto
- services/crypto_create.proto
- services/transaction_record.proto
Signed-off-by: Nana Essilfie-Conduah <nana@swirldslabs.com>
To support the increased support of the alias in the CryptoCreate Transaction
- Add alias bytes to crypto create
- Update `AccountID.alias` description
- Update `TransactionRecord.alias` description
Fixes #222 
**Checklist**
> Add alias bytes to crypto create

- services/custom_fees.proto
- Required for a backward-compatible implementation of [HIP-573](https://hips.hedera.com/hip/hip-573).
> Add `all_collectors_are_exempt` field to `CustomFee` message.

- services/response_code.proto
- Adds a `TRANSACTION_HAS_UNKNOWN_FIELDS` response code to signal when a client has used a not-yet-supported protobuf field.
> Include `TRANSACTION_HAS_UNKNOWN_FIELDS`

- services/custom_fees.proto
- Emphasizes that native NFT royalties are a best-effort convenience feature, not an inescapable fact.
> Add disclaimer on NFT royalty fees

- services/state/token/account.proto
Since `Owner` field is not required for the allowances map on a specific account, added new messages without `Owner` field in `Account` PBJ Object for state.
> Change allowance maps on `Account` PBJ Object

- services/state/token/account.proto
- Add missing fields in `account.proto`
- Change allowance field names
> Add missing fields in Account

- services/state/schedule/schedule.proto
Original commit of this file uses package com.hedera.hapi.node.state.file.
The correct package is com.hedera.hapi.node.state.schedule.
Verified clean build in services with [verify-protos](https://github.com/jsync-swirlds/bash-scripts/blob/swirlds/verify-protos) script.
> Fix package name for state/schedule

- services/state/consensus/topic.proto
- services/state/file/file.proto
Change `long file_number` to `FileID file_id` in file.proto
This is in support of [issue #7098 in the hedera-services repo](https://github.com/hashgraph/hedera-services/issues/7098)
`file.proto` is not part of any previous releases. Therefore there is no need to ensure backwards compatibility.
> Update file.proto to use FileID type instead of long for file identification

- services/state/schedule/schedule.proto
* Changed body_bytes to original_create_transaction
* Changed type to TransactionBody
* Updated comments to clarify several items and correct language
Verified using [verify-protos](https://github.com/jsync-swirlds/public-scripts/blob/addVerifyProtos/verify-protos)
> Adjusting the state Schedule message to improve implementation.

- services/state/token/nft.proto
Use IDs instead of longs for types in nft.proto
Fixes # 7244 in hedera-services repo
See [PR #7288](https://github.com/hashgraph/hedera-services/pull/7288) over in hedera-services 
DO NOT MERGE THIS PR UNTIL AFTER [PR #7288](https://github.com/hashgraph/hedera-services/pull/7288) HAS BEEN MERGED
> Change nft owner and spender identifier from long to AccountID

- services/basic_types.proto
- services/state/common.proto
- services/state/token/account.proto
- services/state/token/nft.proto
- services/token_get_nft_info.proto
1) Move NftID from token_get_nft_info.proto to basic_types.proto
2) Change everywhere that uses UniqueTokenID to use NftID instead
3) Delete UniqueTokenId from common.proto
Fixes [#7346 in hedera-services](https://github.com/hashgraph/hedera-services/issues/7346)
**Note**:
DO NOT MERGE UNTIL AFTER [PR # 7409](https://github.com/hashgraph/hedera-services/pull/7409) has been merged
> Use NftID instead of UniqueTokenId

- services/state/schedule/schedule.proto
* This protobuf is not yet used, so the fields were renumbered for efficient representation.
* This is in support of resolving Issue #5518
> Update Schedule state protobuf to add a wait_for_expiry flag.

- services/state/primitives.proto
- services/state/schedule/schedule.proto
* Added primitive.proto which includes ProtoLong, ProtoInteger, ProtoBoolen, ProtoString, and ProtoBytes.
* Added ScheduleList message to schedule.proto
This is half of the [related issue](https://github.com/hashgraph/hedera-services/issues/7779).  The other half (code changes to use the new protobuf messages and remove Codec implementations) will follow.
> Add Protobuf messages for primitive values and a list of Schedules.

- services/state/primitives.proto
Fixes java_package to "com.hederahashgraph.api.proto.java"
> Fix the "java_package"

- services/crypto_get_account_balance.proto
- services/crypto_get_info.proto
- services/freeze.proto
- services/response_header.proto
- services/state/blockrecords/block_info.proto
- services/state/consensus/topic.proto
- services/state/contract/storage_slot.proto
- services/state/file/file.proto
- services/state/primitives.proto
- services/state/schedule/schedule.proto
- services/state/token/account.proto
- services/state/token/network_staking_rewards.proto
- services/state/token/nft.proto
- services/state/token/staking_node_info.proto
- services/state/token/token.proto
- services/state/token/token_relation.proto
- services/transaction.proto
Clean up files in services/state for consistency in naming
-Rename expiration_time -> expiration_second in several fields where it occurs
-Rename num -> number in several places
-Rename auto_renew_secs -> auto_renew_seconds
-Rename some id fields. All id fields are now of the form [message name]_id
-Remove unused imports
-Edits to comments
Fixes #7684 in hedera-services
DO NOT MERGE until after [PR # 7986](https://github.com/hashgraph/hedera-services/pull/7986) in hedera-services is merged
> protobuf cleanup

- services/state/blockrecords/block_info.proto
There are two properties we need from the mono network context, that have not yet been ported to the modular code. These properties are added to `BlockInfo` here.
> Add migration properties to BlockInfo

- services/contract_call_local.proto
Added fully-qualified name for a type of `ContractFunctionResult.signer_nonce`
Fixes #315
> 315 Added fully-qualified name for a type of `ContractFunctionResult.signer_nonce`

- services/token_create.proto
- services/token_update.proto
- services/token_update_nft.proto
This PR modifies the token_create, token_update 
and creates a new token_nft_update.proto in order to support 
the 3 metadata related HIPs - [646, 657 and 765]
https://github.com/hashgraph/hedera-services/issues/10931
**Fixes**:
https://github.com/hashgraph/hedera-services/issues/10932
**Checklist**
> Protobuf changes for implementation of metadata hips 646, 657 and 765

- services/state/blockrecords/block_info.proto
- We must keep the provisional consensus time of the current block in state so reconnecting nodes can deterministically decide when to close the current block and begin the next one.
> Add `BlockInfo#first_cons_time_of_current_block`

- services/state/token/staking_node_info.proto
Add pendingRewards to StakingNodeInf. It will be updated at midnight when the pendingRewards of all nodes are calculated.
https://github.com/hashgraph/hedera-services/issues/10954
> Add pending rewards per node

- services/state/blockrecords/block_info.proto
- services/state/contract/storage_slot.proto
Change long to ContractID in the SlotKey message. This is necessary to support sharding in the future.
This PR + https://github.com/hashgraph/hedera-services/pull/10958 together fix https://github.com/hashgraph/hedera-services/issues/10746
> Use contract id in slot key

- services/basic_types.proto
- services/token_lock.proto
- services/token_unlock.proto
Change the definitions of TokenLockTransactionBody and TokenUnlockTransactionBody
to allow multiple NFTs to be locked/unlocked with a single call
The format of the new transactions is more aligned with the rest of Token Service.
https://github.com/hashgraph/hedera-services/issues/9636
> HIP 796: Update TokenLock, TokenUnlock TransactionBody Definitions

- platform/event/event_payload.proto
- platform/event/event_payloads.proto
- platform/event/state_signature_payload.proto
As part of the process of moving to protobuf for serialization and the blockstream effort, we start with the definitions of event payloads (formerly transactions).
**Note**:
I accidentally closed the previous PR that was open for this branch https://github.com/hashgraph/hedera-protobufs/pull/331
- https://github.com/hashgraph/hedera-services/issues/12210
> definitions for event payloads

- services/response_code.proto
Create a `TOKEN_HAS_NO_ADMIN_KEY` response code needed after HIP-540
Fixes #339 
Previously, when a token has no admin key on initialization, it is considered to be immutable and when a TokenUpdate is performed to those kind of tokens, we return `TOKEN_IS_IMMUTABLE` error.
After HIP-540, a token without an admin key on initialization is **not** considered immutable when it has a low priority 
on create. In this case a low priority key can update itself even if the token has no admin key.
We need a new response code - `TOKEN_HAS_NO_ADMIN_KEY` for the cases where a token does not have an admin key on create and in TokenUpdate we try to update the admin key. Previously, this resulted in `TOKEN_IS_IMMUTABLE` but after the HIP this …
> HIP-540: add new response code to support

- platform/event/event_consensus_data.proto
closes https://github.com/hashgraph/hedera-services/issues/12982
> chore: added consensus data protobuf

- .gitignore
- services/address_book_service.proto
- services/basic_types.proto
- services/node_create.proto
- services/node_delete.proto
- services/node_get_info.proto
- services/node_update.proto
- services/query.proto
- services/response.proto
- services/response_code.proto
- services/schedulable_transaction_body.proto
- services/state/addressbook/node.proto
- services/token_update_nfts.proto
- services/transaction_body.proto
- services/transaction_receipt.proto
* Updated specification/API comments
A rendered version of the documentation in these files is _temporarily_ available on [another branch](https://github.com/hashgraph/hedera-protobufs/tree/temp-DAB-Update-Spec-Backup/documents/api/services) to assist with visualizing what these changes accomplish.
> feat: Update specification text for address book service

- services/response_code.proto
One response code was inadvertently spelling-corrected in the last PR.
This returns to the former spelling.
> fix: Fixing single-letter mismatch to expectations

- block/block_service.proto
- block/stream/block.proto
- block/stream/block_header.proto
- block/stream/block_item.proto
- block/stream/block_proof.proto
- block/stream/event_metadata.proto
- block/stream/input/system_transaction.proto
- block/stream/output/consensus_service.proto
- block/stream/output/crypto_service.proto
- block/stream/output/file_service.proto
- block/stream/output/network_service.proto
- block/stream/output/schedule_service.proto
- block/stream/output/smart_contract_service.proto
- block/stream/output/state_changes.proto
- block/stream/output/token_service.proto
- block/stream/output/transaction_output.proto
- block/stream/output/transaction_result.proto
- block/stream/output/util_service.proto
This PR makes a few changes to the block stream protobuf definitions to allow PBJ to compile them.
1. ```java_package``` and ```pbj.java_package``` need to be different packages so the compiled java classes in hedera-services don't clash. Same with the generated tests.
2. Fixed two javadoc errors in ```block_header.proto``` and ```state_changes.proto```
3. Moved enum definitons outside of message definition and changed their name's.
Suggest any additional changes or renaming. Thanks for your time.
**Checklist**
> chore: Block Stream protobuf changes for PBJ compiler

- services/basic_types.proto
- services/token_airdrop.proto
- services/token_service.proto
- services/transaction_body.proto
- services/transaction_record.proto
This PR modifies the protobufs in order to support creating Airdrops
https://github.com/hashgraph/hedera-services/issues/13698
Fixes #
Merge this PR after https://github.com/hashgraph/hedera-protobufs/pull/367 is merged in main and this branch is synced with main, otherwise the build in Services develop branch will fail.
**Checklist**
> feat: Protobuf changes for registering airdrop

- services/state/token/account.proto
Just like `num_owned_nfts` account need to track number of pending airdrops on the account, which is needed to calculate rent in the future.
> Add number of pending airdrops on `Account`

- services/state/recordcache/recordcache.proto
As per https://github.com/hashgraph/hedera-services/issues/14541, added `TransactionReceiptEntries` object that will be stored in state. It is needed to reduce the size of receipt cache in state.
> Add TransactionReceiptEntries to RecordCache

- block/stream/output/state_changes.proto
- documents/api/block/stream/output/state_changes.md
* Removed old "entity number" style messages from state changes
* Replaced with recommended alternatives.
* Removed state change cause
Mirrored update for hedera-services is [PR 14827](https://github.com/hashgraph/hedera-services/pull/14827)
> Further block node updates

- services/state/blockstream/block_stream_info.proto
Refines the `BlockStreamInfo` message.
* Removes the `last_block_hash` field since the _N-1_ hash is already contained in `trailing_block_hashes`.
* Removes the `last_` prefix on `block_number` and `block_time` as these values apply to the block with the given number.
* Adds some comments to clarify the purpose of the message.
> fix: refine `BlockStreamInfo` message

- services/state/roster/roster.proto
The variable name has been updated by https://github.com/hashgraph/hedera-services/pull/15465 in the hedera-serivces repo.
> chore: Update roster_entries variable name in  roster.proto

- block/block_service.proto
- block/stream/output/smart_contract_service.proto
- block/stream/output/transaction_result.proto
* Modified `PublishStreamRequest` to permit repeated block items.
* Added a `SubscribeStreamResponseSet` wrapper
* This works around that `oneof` does not permit `repeated` fields.
* Modified `SubscribeStreamResponseSet` to have a `repeated` `BlockItem` list.
* Modify gRPC service design.
* Replace single service with four specific services for modularity
Resolves https://github.com/hashgraph/hedera-block-node/issues/259
Note: A mirror PR will be added to hedera-services once this PR is complete.
> Modifications to Block Stream based on recent work

- services/node_delete.proto
- services/node_update.proto
- services/transaction_receipt.proto
Very small update to fix some documentation-only errors in the protocol buffer specification for Node update/delete and transaction receipt.
> Removed incorrect specification for node id in receipt

- services/token_get_info.proto
Protobuf changes for HIP-796 should not have been sync'ed and need to be reverted.
Fixes #457
> fix: Revert HIP-796 Sync from Services 

- services/state/common.proto
PBJ gets confused by comments above keywords and tries to treat them as messages instead, which fails.  This just removes a couple such comments for expediency.
> fix: Fixed a small issue caused by PBJ not handling comments correctly.

- block/stream/block_proof.proto
- block/stream/output/block_header.proto
The previousBlockHash is no longer required in the Block Stream BlockHeader because it causes a timing problem that prevents optimal parallel thread pipelining in the consensus node and we do not want to hold up creating the block header until that hash is ready. It will continue to be available in the Block Proof however.
Fixes #468
> Remove Previous Block Hash from Header
