hashgraph/hedera-protobufs

services/BasicTypes.proto, streams/AccountBalanceFile.proto
Signed-off-by: tinker-michaelj <michael.tinker@hedera.com>
=> Include decimals in queries of token/account balances and relationships

services/TokenCreate.proto
Visible via `gh-pages` branch [here](https://hashgraph.github.io/hedera-protobufs/#TokenCreate.proto).
Closes https://github.com/hashgraph/hedera-services/issues/974
=> Include Leemon's edits from Services issue #974

services/ResponseCode.proto
Added a response enum code for the hedera services issue https://github.com/hashgraph/hedera-services/issues/1145
=> 00017 d hcs message size

services/BasicTypes.proto, services/ResponseCode.proto, services/SchedulableTransactionBody.proto, services/ScheduleCreate.proto, services/ScheduleDelete.proto, services/ScheduleGetInfo.proto, services/ScheduleSign.proto, services/TransactionBody.proto
Please see the [revised scheduled transactions spec](https://github.com/hashgraph/hedera-services/blob/01155-D-ReviseScheduleProtobufs/docs/scheduled-transactions/revised-spec.md) for more context.
=> Update protobufs to satisfy revised scheduled txns spec

services/BasicTypes.proto
**Summary of the change**
1. File `0.0.101` to be populated with just connectivity and payment info for all nodes.
2. File `0.0.102` to be populated with a full metadata for all nodes.
=> Revise address book types to 0.13.0 standard

services/ResponseCode.proto
Add response codes used by fixes in https://github.com/hashgraph/hedera-services/pull/1787.
=> Response codes for previewnet bugs

services/CustomFees.proto
Fixed typo in comments
Fixes #
N/A
**Checklist**
=> fixed typo

services/BasicTypes.proto, services/CustomFees.proto, services/ResponseCode.proto
- https://github.com/hashgraph/hedera-services/issues/1812
- https://github.com/hashgraph/hedera-services/issues/1814
=> Add more response codes esp for HIP-17 and HIP-18

services/Freeze.proto
=> Tweak comments and variable names for stylistic consistency

sdk/transaction_list.proto
Signed-off-by: Daniel Akhterov <daniel@launchbadge.com>
Adds the SDK `TransactionList` protobuf type.
Fixes #
Once #74 is merged this will need to update the import.
**Checklist**
=> feat: add `TransactionList` type that is used by the SDKs

services/basic_types.proto, services/response_code.proto, services/schedulable_transaction_body.proto, services/token_create.proto, services/token_get_info.proto, services/token_pause.proto, services/token_service.proto, services/token_unpause.proto, services/token_update.proto, services/transaction_body.proto
=> 095 d hip 24

services/response_code.proto, services/throttle_definitions.proto
Signed-off-by: Stoyan Panayotov <stoyan.panayotov@limechain.tech>
Fixes #
**Checklist**
=> Added totalAllowedGasPerSec to throttle_definitions.proto

services/basic_types.proto, services/contract_call_local.proto, services/contract_update.proto, services/freeze.proto, services/freeze_type.proto, services/response_code.proto, services/schedulable_transaction_body.proto, services/token_create.proto, services/token_get_info.proto, services/token_pause.proto, services/token_service.proto, services/token_unpause.proto, services/token_update.proto, services/transaction_body.proto
Try again to sync from `develop`, with commits squashed to please DCO.
=> Squash `0.20.0` changes with proper signoff

services/basic_types.proto, services/crypto_get_info.proto, services/response_code.proto, services/transaction_get_receipt.proto, services/transaction_get_record.proto, services/transaction_record.proto
- Includes protobufs for auto-account creation, ECDSA(secp256k1) key support, and "delegatable" contract keys.
=> Squash release 0.21 w/ signed commit

services/token_create.proto, services/token_update.proto
Update comments 
Fixes #
**Checklist**
=> Update token comments

services/consensus_topic_info.proto, services/contract_get_info.proto, services/crypto_get_info.proto, services/file_get_info.proto, services/schedule_get_info.proto, services/token_get_info.proto, services/token_get_nft_info.proto
- Adds a `bytes ledger_id` field to all entity info responses.
=> Support HIP-33

services/basic_types.proto, services/consensus_topic_info.proto, services/contract_get_info.proto, services/crypto_get_info.proto, services/file_get_info.proto, services/response_code.proto, services/schedule_get_info.proto, services/token_create.proto, services/token_get_info.proto, services/token_get_nft_info.proto, services/token_update.proto
- Squash 0.22 changes so `develop` can resume 0.23 merges.
=> Squash 0.22 changes with signoff (take 2)

services/contract_call_local.proto
HIP-260 changes to track smart contract object state chages
**Checklist**
=> HIP-260: Smart Contract Traceability

services/contract_call_local.proto
=> HIP-260: Smart Contract Traceability (#99)

mirror/mirror_network_service.proto, services/basic_types.proto, services/contract_call.proto, services/contract_call_local.proto, services/crypto_get_info.proto, services/crypto_update.proto, services/response_code.proto, services/schedulable_transaction_body.proto
- Squashes all release 0.23 changes into `main`.
=> Squash changes from to-be-deleted `develop`

services/response_code.proto
Based on latest HIP changes, added additional response codes.
=> Additional response codes for Approval/Allowance

services/basic_types.proto, services/crypto_get_info.proto, services/response_code.proto
- Add new basic types for granted allowances used in AccountInfo
- Remove `PAYER_AND_OWNER_NOT_EQUAL` , since the implementation will support pay to not be same as owner
=> Protobuf changes for Approve/Allowance

services/basic_types.proto, services/crypto_delete_allowance.proto, services/schedulable_transaction_body.proto, services/token_get_nft_info.proto, services/transaction_body.proto
Signed-off-by: Neeharika-Sompalli <neeharika.sompalli@hedera.com>
- Moved `CryptoDeleteAllowance` , `TokenDeleteAllowance` , and `NftDeleteAllowance` outside `CryptoDeleteAllowanceTransactionBody`
- Added `CryptoDeleteAllowanceTransactionBody` to `transaction_body.proto`
- Changed the fields to snake case
- Added `spenderId` to `TokenNftInfo`
=> Address recent changes and review comments

services/response_code.proto, services/schedulable_transaction_body.proto, services/schedule_create.proto, services/schedule_get_info.proto, services/schedule_service.proto, services/schedule_sign.proto
Implement protobuf changes for HIP-423: Long Term Scheduled Transactions
Fixes #183
**Checklist**
=> feat(#183): add changes for long term scheduled transactions

services/contract_call_local.proto, services/ethereum_transaction.proto
Stray paren, snake_case new field in eth transaction
Signed-off-by: Danno Ferrin <danno.ferrin@hedera.com>
Fixes #
**Checklist**
=> Tpyos in Ethereum Transaction

services/node_stake_update.proto
Add rewardRate used to calculate End of Staking Period calculations to `NodeStakeUpdateTransactionBody`
**Checklist**
=> Add rewardRate used to calculate End of Staking Period calculations

services/basic_types.proto, streams/hash_object.proto, streams/record_stream_file.proto, streams/sidecar_file.proto, streams/signature_file.proto
Protobuf class implementation for Record Stream V6.
=> Record Stream V6 Protobufs

services/node_stake_update.proto
- Enriches `NodeStake` message with more information.
- Adds more comments.
=> Add `min_stake`, `max_stake`, and `stake_not_rewarded` fields 

services/response_code.proto
=> Add `STAKING_NOT_ENABLED` response

README.md, services/basic_types.proto, services/crypto_service.proto, services/random_generate.proto, services/response_code.proto, services/schedulable_transaction_body.proto, services/transaction_body.proto, services/transaction_record.proto, services/util_service.proto
Addresses [HIP-351](https://hips.hedera.com/hip/hip-351) changes
1. Added a top level `RandomGenerate` grpc end point and `HederaFunctionality`
2. Add `random_generated_number` to transaction record
=> HIP-351 : RandomGenerate transaction

services/contract_call_local.proto, streams/contract_action.proto, streams/contract_bytecode.proto, streams/contract_state_change.proto, streams/record_stream_file.proto, streams/sidecar_file.proto
Traceability extension protobufs
Fixes #
**Checklist**
=> Traceability extension protobufs

services/basic_types.proto, services/prng.proto, services/prng_generate.proto, services/response_code.proto, services/schedulable_transaction_body.proto, services/transaction_body.proto, services/transaction_record.proto, services/util_service.proto
Update name of `RandomGenerate` transaction to `PrngGenerate` transaction as per latest discussion.
=> Update transaction name for HIP-351

.github/CODEOWNERS, .gitignore
Adds a code owner policy to the `main` branch. Updates the `.gitignore` definitions.
Fixes #225
=> Add Code Owner policy

services/response_code.proto
- Adds `INSUFFICIENT_BALANCES_FOR_STORAGE_RENT` and `MAX_CHILD_RECORDS_EXCEEDED`.
=> Add response codes for resource usage limits

services/response_code.proto
Signed-off-by: Neeharika-Sompalli <neeharika.sompalli@swirldslabs.com>
Adds a response code `INSUFFICIENT_BALANCES_FOR_RENEWAL_FEES`
=> Add response code `INSUFFICIENT_BALANCES_FOR_RENEWAL_FEES`

services/token_burn.proto, services/token_mint.proto, services/token_wipe_account.proto
Updates the documentation for HIP-564 changes
=> Update documentation for HIP-564

services/crypto_create.proto, services/crypto_get_info.proto, services/crypto_update.proto, services/file_create.proto, services/file_get_info.proto, services/file_update.proto
- Temporarily removes auto-renew metadata for files and accounts.
=> Temporarily remove auto-renew fields for files, accounts for `v0.34.0` tag

services/response_code.proto
Signed-off-by: Stoyan Panayotov <stoyan.panayotov@limechain.tech>
Fixes #
**Checklist**
=> Add ALIAS_ALREADY_ASSIGNED status to response codes proto definition

services/state/file/file.proto
createed a protobuf for the file service
Related issue(s):
#265
=> file proto

services/state/file/file.proto
=> fix some comments on file proto

services/state/schedule/schedule.proto
new schedule proto for scheduler for modularization
Fixes #279
=> add schedule proto

services/state/schedule/schedule.proto
Fixed missing import and incorrect message name.
This time the code was verified against services, so should compile without issues.
=> Adding missed import statement.

services/state/consensus/topic.proto
change topic number to topicID in protobuf
https://github.com/hashgraph/hedera-services/issues/7104
=> change topic number to topicID

services/state/common.proto, services/state/token/token.proto, services/state/token/token_relation.proto
DO NOT DELETE 7242-update-common-ids BRANCH YET
Update common.proto and classes that rely on it to use AccountID and TokenID instead of long.
Update token.proto and classes that rely on it to use AccountID and TokenID instead of long.
Update token_relation.proto and classes that rely on it to use AccountID and TokenID instead of long
**Checklist**
=> Update common.proto, token.proto, token-relation.protp and classes that rely on it to use AccountID and TokenID

services/state/consensus/topic.proto
changed auto_renew_account_number to auto_renew_account_id in topic.proto
Fixes #
**Checklist**
=> changed auto_renew_account_number to auto_renew_account_id in topic.proto

services/state/blockrecords/block_info.proto, services/state/token/account.proto
updated *.proto to use *_number through all the services/state
Standardize to use snake case throughout all the *.proto files under services\state
Added staked_id, removed staked_number in account.proto
Fixes #
Related to hedera-services issue 7423, 7343.
**Checklist**
=> use snake case throughout protobufs

services/node_stake_update.proto
- Adds protobuf changes needed for [HIP-786](https://hips.hedera.com/hip/hip-786).
=> Update `NodeStakeUpdateTransactionBody` fields for HIP-786

services/basic_types.proto
Add a HederaFunctionality type that was inadvertently omitted.
[Issue #8155](https://github.com/hashgraph/hedera-services/issues/8155) in hedera-services
Part of epic [issue #7680](https://github.com/hashgraph/hedera-services/issues/7680) in hedera-services
=> Add TransactionGetFastRecord to HederaFunctionality

services/basic_types.proto, services/state/file/file.proto
=> Revert `NftID#tokenId` to `NftID#tokenID`

services/state/congestion/congestion_level_starts.proto, services/state/throttles/throttle_usage_snapshots.proto
- https://github.com/hashgraph/hedera-services/issues/7962
**Checklist**
=> Add throttle and congestion types

services/contract_call_local.proto
Add new field defined in [HIP-844](https://github.com/hashgraph/hedera-improvement-proposal/pull/844/files?short_path=442ac4b#diff-442ac4b6374cc22d6c854ed7c8c42c4fec3fc6ed4e74693593e1d6293db8926b). 
Fixes #
**Checklist**
=> feat: HIP-844 - add signer_nonce field to message ContractFunctionResult

services/contract_call_local.proto
Sync with updates from `main` branch
=> Sync with updates from `main` branch

services/contract_call_local.proto
=> Sync with changes from main

services/response_code.proto, services/state/token/token.proto, services/token_create.proto, services/token_get_info.proto, services/token_service.proto
This reverts commit ffbd48e70bd5b7bdd292523de939181678600037.
Fixes #
**Checklist**
=> Revert "Metadata hips 646 657 765 (#319)"

.github/CODEOWNERS
This pull request changes the following:
- Adds a code owner definition for the `/platform/` folder.
=> chore: update codeowner definitions for the Platform protobuf files

services/basic_types.proto, services/query.proto
Added NodeGetInfo to HederaFunctionality, added NodeGetInfoQuery to query.proto
Fixes #
**Checklist**
=> Added NodeGetInfo

services/crypto_create.proto, services/crypto_update.proto, services/response_code.proto
=> feat: HIP-904 maxAutoAssociations updates

services/basic_types.proto, services/response_code.proto, services/token_reject.proto, services/token_service.proto
=> feat: add token reject transaction

services/schedulable_transaction_body.proto, services/transaction_body.proto
This PR adds missing TokenRejectTransactionBody to transaction_body proto
Fixes #
**Checklist**
=> feat: add TokenRejectTransactionBody to transaction_body proto

services/response.proto
added NodeGetInfoResponse to response.proto
fix #356
=> feat: added NodeGetInfoResponse to response.proto

services/basic_types.proto
Pending Airdrops protobuf changes for state
https://github.com/hashgraph/hedera-services/issues/13113
**Checklist**
=> Hip 904 pending airdrops protobuf changes

services/response_code.proto
=> Added more response codes for Dynamic Address Book Phase 2

services/contract_create.proto, services/contract_update.proto
Similar updates to `ContractCreate` & `ContractUpdate` doc comments as in https://github.com/hashgraph/hedera-protobufs/pull/348.
Fixes #
**Checklist**
=> feat: maxAutoAssociations updates for contract transactions

services/response_code.proto
Adds new status for TokenReject for the case where the transaction attempts to add more than allowed rejections/token references to the List.
Fixes #
**Checklist**
=> feat: Add Reference limit exceeded as a response code 

services/response_code.proto
=> feat: Add more response codes for Dynamic Address Book Phase 2

services/response_code.proto
=> fixed INVALID_GOSSIP_CA_CERTIFICATE

.github/CODEOWNERS
Updated to include devops-ci in codeowners
=> chore: Updated codeowners to include devops-ci

services/response_code.proto
Addition of new `ResponseCodeEnum` value of `TOKEN_HAS_NO_METADATA_OR_SUPPLY_KEY` to support implementation of [HIP-850](https://hips.hedera.com/hip/hip-850)
See https://github.com/hashgraph/hedera-services/pull/14204
**Checklist**
=> feat: HIP-850: HTS mutable metadata in treasury

.github/CODEOWNERS
Updates codeowners file
Fixes #398
=> chore: Q3 DevOps CI/CD Audit Updates

services/response_code.proto, services/state/recordcache/recordcache.proto
Add more response codes for airdrops
=> Add more response codes

block/stream/output/state_changes.proto, services/response_code.proto
* Transaction record entries replaced with transaction receipt entries in the block stream
* Platform state changes added to the block stream
* Additional response codes for airdrop and throttle failures added.
=> Adding updates from hedera-services

block/stream/output/state_changes.proto
- Adds state ids and value types for the `RosterService`.
=> fix: Include `RosterService` state changes

services/auxiliary/tss/tss_message.proto, services/state/roster/ledger_id.proto, services/state/tss/tss_vote_map_key.proto
=> Line Break formatting fix for Tss Protos comments

services/address_book_service.proto, services/node_update.proto
Sync with hedera-services protobuf changes.
#427 
**Checklist**
=> updateNode needs both admin key and council to sign

block/block_service.proto, block/stream/output/block_header.proto, block/stream/output/consensus_service.proto, block/stream/output/schedule_service.proto, block/stream/output/smart_contract_service.proto, block/stream/output/token_service.proto, block/stream/output/transaction_output.proto, block/stream/output/transaction_result.proto, services/basic_types.proto, services/state/blockstream/block_stream_info.proto, services/state/recordcache/recordcache.proto, services/state/tss/tss_vote_map_key.proto
* Copied recent changes
* Fixed several small errors (incorrect indentation, malformed break tags, etc...)
* Applied temporary workaround for PBJ bug 280
=> chore: Copied recent protobuf changes from hedera-services

block/block_service.proto
* Removed commented items in block_service that PBJ fouls up.
=> chore: Remove commented field and sub-message

services/address_book_service.proto, services/node_update.proto
Sync protobuf changes from PR 16495.
Fixes #
**Checklist**
=> Sync 16495 protobuf change

services/node_delete.proto
Sync hedera-services change in pr, feat: change DAB node delete transaction sign requirement (PR #16953)
Fixes #
**Checklist**
=> Sync PR 16953 proto change

block/stream/record_file_item.proto
* Added `RecordFileSignature` message for record file signatures
* Modified sidecar file to use `SidecarFile` from streams v6.
=> chore: Record File Items update based on conversion experience.

block/block_service.proto, block/stream/output/block_header.proto, block/stream/output/consensus_service.proto, block/stream/output/crypto_service.proto, block/stream/output/state_changes.proto, block/stream/output/token_service.proto, block/stream/output/transaction_output.proto, block/stream/output/transaction_result.proto, platform/event/event_transaction.proto, platform/state/platform_state.proto, services/basic_types.proto, services/node_create.proto, services/node_update.proto, services/response_code.proto, services/state/addressbook/node.proto, services/state/history/history_types.proto, services/state/token/network_staking_rewards.proto, services/state/token/node_rewards.proto, services/transaction.proto, services/util_service.proto
This PR syncs the protobuf changes from the hiero-consensus-node repo for release 61.
Includes updates across block streams, HIP-1064, hints/history/crs, HIP-551, platform.
Fixes #
**Checklist**
Signed-off-by: Derek Riley <derek.riley@swirldslabs.com>
=> chore: Release 0.61 Updates
